- hosts: all
  become: true

  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.git
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: robertdebock.bootstrap
    - role: robertdebock.locale
    - role: geerlingguy.jenkins
