- name: Get system locale settings
  become: yes
  shell: localectl status
  register: LOCALE_VARS
  changed_when: false


- name: Change system locale
  become: yes
  shell: "localectl set-locale LANG={{ system_locale }}"
  when: system_locale in LOCALE_VARS

- name: Apply system locale
  become: yes
  shell: source /etc/locale.conf
  when: system_locale in LOCALE_VARS
