- name: Install Java with yum | default settings install OpenJDK
  yum:
    name: '{{ java_version }}'
    state: present

- name: Add the Jenkins repository to the yum repos
  yum_repository:
    name: jenkins
    description: Jenkins-stable
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgcheck: yes
    gpgkey: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

- name: Install Jenkins with yum
  yum:
    name: jenkins
    state: present

- name: Add jenkins to docker group
  user:
    name: jenkins
    group: docker

- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: yes
