---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: ${PLATFORM_NAME}
    image: ${AMI_ID}
    instance_type: t2.small
    vpc_subnet_id: ${VPC_SUBNET_ID}
    keypair_name: ${KEYPAIR_NAME}
    security_group_name: ${SECURITY_GROUP_NAME}
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: ansible.posix.profile_tasks
  connection_options:
    jenkins_plugins:
      - greenballs
      - ghprb
      - workflow-aggregator
      - aws-codebuild
      - pipeline-aws
      - aws-cloudwatch-logs-publisher
      - aws-lambda
      - snsnotify
      - blueocean
      - docker-workflow
      - slack
      - global-slack-notifier
  log: true
  playbooks:
    converge: ../../install.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - cleanup
    - destroy
